# Generated by Django 4.2.1 on 2023-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snotelsite',
            name='elevation',
        ),
        migrations.AddField(
            model_name='snotelsite',
            name='elevation_m',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snotelsite',
            name='site_id',
            field=models.CharField(default='dd', max_length=100),
            preserve_default=False,
        ),
    ]
