# Generated by Django 4.2.1 on 2023-05-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_remove_snotelsite_elevation_snotelsite_elevation_m_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnotelData',
        ),
        migrations.DeleteModel(
            name='SnotelSite',
        ),
    ]
