# Generated by Django 4.2.1 on 2023-05-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahub', '0003_delete_snoteldata_delete_snotelsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnotelSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elevation_m', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SnotelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('snow_depth', models.FloatField()),
                ('timestamp_utc', models.DateTimeField()),
                ('snotel_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.snotelsite')),
            ],
        ),
    ]
