# Generated by Django 4.2.1 on 2023-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snotelsite',
            name='id',
        ),
        migrations.AlterField(
            model_name='snotelsite',
            name='site_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
