# Generated by Django 4.2.1 on 2023-05-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_remove_snotelsite_id_alter_snotelsite_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snoteldata',
            old_name='snotel_site',
            new_name='site_id',
        ),
        migrations.AlterField(
            model_name='snoteldata',
            name='snow_depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='snoteldata',
            name='temp',
            field=models.FloatField(null=True),
        ),
    ]
