# Generated by Django 4.2.1 on 2023-05-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0011_alter_snoteldata_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snoteldata',
            name='site',
        ),
        migrations.AddField(
            model_name='snoteldata',
            name='snotel_site',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='datahub.snotelsite'),
            preserve_default=False,
        ),
    ]
