# Generated by Django 4.2.1 on 2023-06-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0012_remove_snoteldata_site_snoteldata_snotel_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snoteldata',
            old_name='timestamp_utc',
            new_name='timestamp_local',
        ),
        migrations.RenameField(
            model_name='snotelsite',
            old_name='elevation_m',
            new_name='elevation_ft',
        ),
    ]
