# Generated by Django 4.2.1 on 2023-06-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0013_rename_timestamp_utc_snoteldata_timestamp_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snoteldata',
            old_name='timestamp_local',
            new_name='timestamp',
        ),
    ]
